#!/bin/bash

install_packages(){
  declare -A osInfo;
  osInfo[/etc/debian_version]="apt-get install -y"
  osInfo[/etc/alpine-release]="apk --update add"
  osInfo[/etc/centos-release]="yum install -y"
  osInfo[/etc/fedora-release]="dnf install -y"

  for f in ${!osInfo[@]}
  do
      if [[ -f $f ]];then
          package_manager=${osInfo[$f]}
      fi
  done

  package="git tmux vim"

  sudo ${package_manager} ${package}
}

clone_mainrepo(){
  mkdir -p $HOME/github/Akegata/conf
  git clone https://github.com/Akegata/conf.git $HOME/github/Akegata/conf
}

create_symlinks(){
  if [ -f "$HOME/.tmux.conf" ]; then
    mv $HOME/.tmux.conf $HOME/.tmux.conf.bak
  fi
  ln -s $HOME/github/Akegata/conf/tmux/.tmux.conf $HOME/.tmux.conf

  if [ -f "$HOME/.vimrc" ]; then
    mv $HOME/.vimrc $HOME/.vimrc.bak
  fi
  ln -s $HOME/github/Akegata/conf/vim/.vimrc $HOME/.vimrc
}

install_tmuxconf(){
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}

install_vimconf(){
  mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
  git clone https://github.com/tpope/vim-sensible.git $HOME/.vim/bundle/
  git clone https://github.com/rodjek/vim-puppet.git $HOME/.vim/bundle/
}

install_packages
clone_mainrepo
create_symlinks
install_tmuxconf
install_vimconf
